; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; ESP32-S3 Super Mini with 4MB flash
[env:esp32-s3-mini]
platform = espressif32
board = lolin_s3_mini ;similar board to the one we have with 4mb of flash to match our 4mb flash module
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; TMCStepper library for TMC2209 driver control
lib_deps = 
    teemuatlut/TMCStepper@^0.7.3

; Build flags - Force USB-CDC mode
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
